library(iNEXT)
library(readxl)
Transecto <- read_excel("pedrovogeley/analises-certas/Transecto.xlsx")
View(Transecto)
Mata <- read_excel("pedrovogeley/analises-certas/Mata.xlsx")
View(Mata)
CO <- read_excel("pedrovogeley/analises-certas/CO.xlsx")
View(CO)
dadotransecto <-iNEXT(Transecto$conta, q=0, datatype = "abundance")
ggiNEXT(dadotransecto, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE)
dadomata <-iNEXT(Mata$conta, q=0, datatype = "abundance")
ggiNEXT(dadomata, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE)  
dadoco <-iNEXT(CO$conta, q=0, datatype = "abundance")
ggiNEXT(dadoco, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE) 

dadotransecto1000 <- iNEXT(Transecto$conta, q=0, datatype = "abundance", endpoint = 1000)
ggiNEXT(dadotransecto1000, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE)
dadomata1000 <- iNEXT(Mata$conta, q=0, datatype = "abundance", endpoint = 1000)
ggiNEXT(dadomata1000, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE)
dadoco1000 <- iNEXT(CO$conta, q=0, datatype = "abundance", endpoint = 1000)
ggiNEXT(dadoco1000, type=1, se=TRUE, facet.var="none", color.var="site", grey=FALSE)
